spring.application.name=shopping

# DB接続情報
spring.datasource.url=jdbc:mysql://localhost:3306/shopping
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=shinzato
spring.datasource.password=0515

# 実行されたSQLをコンソールに表示する
spring.jpa.show-sql=true

# 表示されるSQLを改行して見やすく整形（フォーマット）する
spring.jpa.properties.hibernate.format_sql=true

# SQLに埋め込まれたパラメータ（? の部分）の具体的な値を表示する
logging.level.org.hibernate.orm.jdbc.bind=trace